### ISSUE TITLE
Investigate knotd corner cases

### ISSUE THREAD

**Issue by vitbaq** [CESARBR/knot-service-source#28]
Output: List of discovered corner cases.

**Comment by vitbaq** [comment]
- Discard message when the device doesn't exist.
- Discard message when the device is offline.

**Comment by vitbaq** [comment]
on cloud_unregister_device: Put json parse on parse.c

**Comment by vitbaq** [comment]
- Change prefix amqp_ on amqp.c/h;
- cloud_msg_destoy (same list with different types);
- on_cloud_reveive (rework if(!session...  and comment that the connexion with amqp queue is always active);
- handle_device_added always return true;
- cloud_auth_device (all cloud_* functions): memory leak if failure;
- Remove downstream_callback;
- Handle amqp server disconnect

**Comment by ramonhpr** [comment]
Rollback should remove device_id_list not just remove from JSON

**Comment by ramonhpr** [comment]
Send signal dbus when receiving an error from cloud/fog
