### ISSUE TITLE
Investigate RabbitMQ integration

### ISSUE THREAD

**Issue by joaoaneto** [CESARBR/knot-service-source#5]
As a developer, I want to understand how to use the rabbitmq-c library in order to communicate with the RabbitMQ server.

DoD:

- [x] Create basic examples with the library
- [x] Create examples with libell
- [x] Define new internal architecture
- [x] Define stories

**Comment by vitbaq** [comment]
Helpful links:
http://alanxz.github.io/rabbitmq-c/docs/0.8.0/index.html
examples: https://github.com/alanxz/rabbitmq-c/tree/master/examples
amqp reference: https://www.rabbitmq.com/amqp-0-9-1-reference.html

Suggested stories (by @ramonhpr):
S1: Bootstrap integration with rabbitmq-c library
* Add dependency :white_check_mark:
* Start/stop connection :white_check_mark:
* add option --rabbitmq-url :white_check_mark:
* Verify corner cases (eg. try to reconnect to rabbitmq when it disconnect)
S2: Send 'data' messages to message queue
• Replace msg_data to use rabbitmq
• Declare exchange fog-messages
• Remove parsing function from proto.c to parser.c
• Publish on binding key data.publish :white_check_mark:
• create function rabbitmq_publish_persistent_message :white_check_mark:
• Verify how we gonna do with timevalue in data message
S3: Receive commands from message queue
* Replace msg_get_data to use rabbitmq
* Replace msg_set_data to use rabbitmq
* Bind exchange fog-messages
* Listen to binding key data.update
* Listen to binding key data.requested
S4: Send 'schema' message to message queue
• Replace msg_schema to use rabbitmq
• publish to cloud-messages with key binding schema.update
S5: Send 'register' message to message queue
* Replace msg_register to use rabbitmq
* Listen to exchange devices.registered
* implement devices.registered on connector
S6: Send 'unregister' message to message queue
• Replace msg_unregister to use rabbitmq
• publish to device.unregister
S6: Authenticate devices
* List devices on start
* Send 'authenticate' command to message queue
* Implement 'authenticate' on connector
S7: Remove leftover code
• Remove ws dependency and files proto_*
• Remove dbus set localhost, port, uuid and token
• verify if proxy.c and parse.c can be removed
